server:
    servlet:
        context-path: /${spring.application.name}
spring:
    application:
        name: api
    datasource:
        url: jdbc:h2:mem:survey-db
        username: app
        password: 'app'
    h2:
        console:
            enabled: true
            path: /h2-console
    jpa:
        properties:
            hibernate:
                format-sql: true
        show-sql: false

springdoc:
    api-docs:
        path: /docs