name: Auto Create PR

on:
  push:
    branches:
      - master

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          head: master
          base: develope
          title: "Auto PR: Merge feature into main"
          body: "This is an automated pull request to merge the `feature` branch into `main`."
          github_token: ${{ secrets.GITHUB_TOKEN }}