name: Docker Hub Pipeline
on: push

jobs:
  docker-hub-pipeline:
    name: Pipeline
    uses: maurigvs/ga-self-service/.github/workflows/docker-hub-pipeline.yml@breaking-docker-pipeline
    secrets: inherit
    permissions:
      contents: write
      packages: write