name: Docker Hub Publisher
run-name: ${{ github.ref_name }}

on:
  push:
    branches:
      - v4.0

jobs:
  publisher:
    name: Publisher
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checking out ${{ github.repository }}
        uses: actions/checkout@v4

      - name: Setting up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Build and Test
#        run: ./gradlew build --no-daemon --console plain
        run: ./gradlew -b ci.gradle package

      - name: Setting up Docker
        uses: docker/setup-buildx-action@v3

      - name: Docker Hub Logon
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.TOKEN }}

      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ github.repository }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
