name: Docker Hub Pipeline
on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker-hub-pipeline:
    name: Pipeline concurrent
    uses: maurigvs/ga-self-service/.github/workflows/docker-hub-pipeline.yml@main
    secrets: inherit
    permissions:
      contents: write
      packages: write
