name: Docker Image CI

on:
  workflow_call:

env:
  IMAGE_TAG: ${{ github.repository }}:latest

jobs:
  build-gradle:
    uses: maurigvs/survey-api/.github/workflows/gradle.yml@v2.0

  build-image:
    runs-on: ubuntu-latest
    steps:
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ env.IMAGE_TAG }}
