name: Docker Pipeline v2
run-name: Building ${{ github.ref_name }}
on: workflow_dispatch

jobs:
  build-push-image:
    name: Build and Push
    uses: maurigvs/ga-self-service/.github/workflows/build-push-image.yml@main
    secrets: inherit
    permissions:
      contents: read
      packages: write