name: Docker Image CI

on:
  workflow_call:

env:
  IMAGE_TAG: ${{ github.repository }}:latest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: maurigvs/survey-api/.github/workflows/gradle.yml@v2.0

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ env.IMAGE_TAG }}
