name: Docker Pipeline v2

on: workflow_dispatch

jobs:
  build-push-image:
    name: Docker Build & Push
    uses: maurigvs/ga-self-service/.github/workflows/build-push-image.yml@main
    secrets: inherit
    permissions:
      contents: read
      packages: write