name: Build Test

on:
  workflow_call:
    secrets:
      USER:
        required: true
      TOKEN:
        required: true

jobs:
  build-test:
    name: Build Test
    runs-on: ubuntu-latest

    permissions:
      contents: read

    env:
      java-version: '17'
      java-dist: 'temurin'

    steps:
      - name: Checking out ${{ github.repository }}
        uses: actions/checkout@v4

      - name: Setting up Java ${{ env.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.java-version }}
          distribution: ${{ env.java-dist }}

      - name: Setting up Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          dependency-graph: generate-and-submit

      - name: Build with Gradle
        run: ./gradlew build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: ${{ vars.REGISTRY }} login
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.TOKEN }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ github.repository }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max