name: Docker

on:
  push:
    branches: [ "master" ]

env:
  # Use docker.io for Docker Hub if empty
  # REGISTRY: ghcr.io  
  REGISTRY: docker.io
  
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      # Build latest version of survey-api
      - name: Docker Image CI
        uses: ./docker-image.yml@master

      # Login against a Docker registry except on PR / https://github.com/docker/login-action
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push Docker image with Buildx (don't push on PR) / https://github.com/docker/build-push-action
      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ github.repository }}:latest
