name: Build and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - v2.0

jobs:
  pipeline:
    runs-on: ubuntu-latest
    
    steps:
      - uses: ${{ github.repository }}/.github/workflows/gradle.yml@v2.0
      - uses: ${{ github.repository }}/.github/workflows/docker-image.yml@v2.0
      - uses: ${{ github.repository }}/.github/workflows/docker-publish.yml@v2.0