name: Build and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - v2.0

jobs:
  build-gradle:
    uses: maurigvs/survey-api/.github/workflows/gradle.yml@v2.0
  build-image:
    uses: maurigvs/survey-api/.github/workflows/docker-image.yml@v2.0
  push-image:
    uses: maurigvs/survey-api/.github/workflows/docker-publish.yml@v2.0
    permissions:
      packages: write
      id-token: write