name: Build and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - v2.0

env:
  IMAGE_TAG: ${{ github.repository }}:latest

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle Wrapper
        run: ./gradlew build

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ env.IMAGE_TAG }}