name: Build and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - v2.0

jobs:
  pipeline:
    runs-on: ubuntu-latest
    
    steps:
      - uses: gradle.yml@master
      - uses: docker-image.yml@master
      - uses: docker-publish.yml@master
