name: Build and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - v2.0

jobs:
  build-image:
    uses: maurigvs/survey-api/.github/workflows/docker-image.yml@v2.0
  push-image:
    uses: maurigvs/survey-api/.github/workflows/docker-publish.yml@v2.0
    needs:
      - build-image
    permissions:
      packages: write
      contents: read
      id-token: write