name: Build and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - v2.0

env:
  context: ${{ github.repository }}/.github/workflows
  version: v2.0

jobs:
  pipeline:
    runs-on: ubuntu-latest
    
    steps:
      - uses: ${{ env.context }}/gradle.yml@${{ env.version }}
      - uses: ${{ env.context }}/docker-image.yml@${{ env.version }}
      - uses: ${{ env.context }}/docker-publish.yml@${{ env.version }}