on:
  push:
    branches:
      - github-actions
jobs:
  push-to-docker:
    name: Push to Docker
    runs-on: ubuntu-latest

    permissions:
      contents: read

    env:
      java-version: '17'
      java-dist: 'temurin'

    steps:
      - uses: ./.github/workflows/build-app.yml

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in ${{ vars.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ github.repository }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max