name: Retrofit

on:
  pull_request:
    branches: [master]
    types: [closed]

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  retrofit:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.PAT }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Check for existing PRs
        id: check-pr
        run: |
          PRS=$(gh pr list --state open --base develop --json number -q '.[].number')
          if [ -n "$PRS" ]; then
          OLDEST_PR=$(echo "$PRS" | head -n 1)
          echo "oldest_pr=$OLDEST_PR" >> $GITHUB_OUTPUT
          fi
          
          - name: Close oldest PR if exists
            if: steps.check-pr.outputs.oldest_pr != ''
            run: |
              gh pr close ${{ steps.check-pr.outputs.oldest_pr }}
      
      - name: Merge master into develop
        run: |
          git pull
          gh pr create --title "Merge master into develop" --fill --base develop --assignee @me
