name: Build and Run Tests

on:
  push:
    branches:
      - v2.0

jobs:
  build:
    name: Build and Run Tests
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build and Run Tests
        run: ./gradlew test

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'