name: Branch Syncronizer

on:
  push:
    branches:
      - master

jobs:
  retro-fit-merge:
    runs-on: ubuntu-latest
    permissions: write-all
    env:
      GITHUB_TOKEN: ${{ secrets.SURVEY_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      - name: Set Git config
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"

      - name: Merge master back to dev
        run: |
          git fetch --unshallow
          git checkout develop
          git pull
          git merge --no-ff master -m "Automatic retrofit merge"
          git push
